### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Annabxlla** [redraskal/r6-dissect-bun#1]
```
panic: runtime error: index out of range [-1]

goroutine 17 [running, locked to thread]:
github.com/redraskal/r6-dissect/dissect.(*Reader).roundEnd(0xc000233b00)
        /github/workspace/dissect/time.go:58 +0xa25
github.com/redraskal/r6-dissect/dissect.(*Reader).Read(0xc000233b00)
        /github/workspace/dissect/reader.go:144 +0x525
main.dissect_read(0x0?)
        /github/workspace/exports/exports.go:76 +0x185
Aborted
```

This happened by following README.md

**Comment by redraskal** [comment]
should be resolved, this was a bug in the Go project just fixed by the latest release on GitHub and npm.

lmk if there are still problems when using the Bun package
